{{- if and .Values.postgresql.internal .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata: { name: kitesync-pgbackrest }
data:
  pgbackrest.conf: |
    [kitesync]
    pg1-path=/var/lib/postgresql/data

    [global]
    repo1-type=s3
    repo1-s3-bucket={{ .Values.backup.s3.bucket }}
    repo1-s3-endpoint={{ regexReplaceAll "^https?://([^/:]+).*$" .Values.backup.s3.endpoint "$1" }}
    repo1-s3-region=us-east-1
    repo1-s3-uri-style=path
    repo1-storage-port={{ .Values.backup.s3.port }}
    repo1-storage-verify-tls={{ ternary "y" "n" (hasPrefix "https://" .Values.backup.s3.endpoint) }}
    repo1-retention-full={{ .Values.postgresql.pgBackRest.retentionFull }}
    start-fast=y
    process-max=2
    log-level-console=info
{{- end }}
