apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitesync
  labels: {{- include "kitesync.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitesync-backup
  labels: {{- include "kitesync.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kitesync-backup
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kitesync-backup
subjects:
  - kind: ServiceAccount
    name: kitesync-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kitesync-backup
